"""init

Revision ID: 3227a99c9ae6
Revises: a0450b796556
Create Date: 2020-07-04 02:37:21.860328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3227a99c9ae6"
down_revision = "a0450b796556"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
