"""init

Revision ID: 3edd1ab465e2
Revises: 
Create Date: 2020-07-02 18:16:49.417784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3edd1ab465e2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("secret_question", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("secret_answer", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "decks",
        sa.Column("id", sa.String(length=8), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deck_id", sa.String(length=8), nullable=False),
        sa.Column(
            "type",
            sa.Enum("relationship", "possession", "action", "feeling", name="cardtype"),
            nullable=True,
        ),
        sa.Column("text", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["deck_id"], ["decks.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "games",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("changeling_deck_id", sa.String(), nullable=True),
        sa.Column("child_deck_id", sa.String(), nullable=True),
        sa.Column("current_round", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["changeling_deck_id"], ["decks.id"],),
        sa.ForeignKeyConstraint(["child_deck_id"], ["decks.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rounds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.String(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "not_ready",
                "self_cards_chosen",
                "other_cards_chosen",
                "ready",
                "complete",
                name="gamestate",
            ),
            nullable=True,
        ),
        sa.Column("changeling_hand", sa.PickleType(), nullable=True),
        sa.Column("child_hand", sa.PickleType(), nullable=True),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rounds")
    op.drop_table("games")
    op.drop_table("cards")
    op.drop_table("decks")
    op.drop_table("users")
    # ### end Alembic commands ###
