"""adds foreign key to cards in hand

Revision ID: c76b9420f23b
Revises: 68c396ebe093
Create Date: 2020-06-29 12:18:54.721246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76b9420f23b'
down_revision = '68c396ebe093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('changeling_waiting', sa.Enum('not_ready', 'ready', 'waiting', 'complete', name='playerstate'), nullable=True),
    sa.Column('child_waiting', sa.Enum('not_ready', 'ready', 'waiting', 'complete', name='playerstate'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards_in_hands',
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('player', sa.Enum('child', 'changeling', name='playertype'), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], )
    )
    op.create_table('games',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('changeling_deck_id', sa.String(), nullable=True),
    sa.Column('child_deck_id', sa.String(), nullable=True),
    sa.Column('rounds', sa.Integer(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changeling_deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['child_deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['rounds'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('cards_in_hands')
    op.drop_table('rounds')
    # ### end Alembic commands ###
