"""game_id

Revision ID: cd6a530416e4
Revises: 5b1c7bf2e174
Create Date: 2020-07-01 13:07:40.771242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cd6a530416e4"
down_revision = "5b1c7bf2e174"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
